name: Build Hammer

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            # name to show in the logs
            buildname: 'linux'
            # qml.net version to use from https://github.com/qmlnet/qt-runtimes/releases/tag/releases
            qt-version: '5.15.1-7fc8b10'
            # .NET platform identifier
            dotnet-platform: 'linux-x64'
            # .NET platform version:
            dotnet-version: 'net5.0'
            # resulting zip or executable name
            deployment-platform: 'linux'
          - os: macos-10.15
            buildname: 'macos'
            qt-version: '5.15.1-7fc8b10'
            dotnet-platform: 'osx-x64'
            dotnet-version: 'net5.0'
            deployment-platform: 'macos'
          - os: windows-2019
            buildname: 'windows'
            qt-version: '5.15.1-7fc8b10'
            dotnet-platform: 'win-x64'
            dotnet-version: 'net5.0'
            deployment-platform: 'windows'

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.4

    - name: Restore maven cache
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x

    - name: Clone Java validator
      run: git clone --depth 1 --shallow-submodules https://github.com/health-validator/org.hl7.fhir.core

      # build Java first as it's needed by .NET for copying into the publish folder
    - name: Build Java validator
      shell: bash
      run: |
        cd org.hl7.fhir.core
        echo "Git revision of the validator code: $(git rev-parse HEAD)"
        mvn package -Dmaven.test.skip=true --projects org.hl7.fhir.validation.cli --no-transfer-progress
        mv org.hl7.fhir.validation.cli/target/org.hl7.fhir.validation.cli*-SNAPSHOT.jar $GITHUB_WORKSPACE/org.hl7.fhir.validator.jar
        cd $GITHUB_WORKSPACE
        java -jar org.hl7.fhir.validator.jar

    - name: (Linux) Build Hammer
      if: runner.os == 'Linux'
      run: |
        sed -i 's|// import appmodel 1.0|import appmodel 1.0|g' Main.qml
        dotnet publish --configuration Release --runtime ${{matrix.dotnet-platform}}

    - name: (macOS) Build Hammer
      if: runner.os == 'macOS'
      run: |
        sed -i '' 's|// import appmodel 1.0|import appmodel 1.0|g' Main.qml
        dotnet publish --configuration Release --runtime ${{matrix.dotnet-platform}}

    - name: (Windows) Build Hammer
      if: runner.os == 'Windows'
      run: |
        sed -i 's|// import appmodel 1.0|import appmodel 1.0|g' Main.qml
        dotnet publish --configuration Release --runtime ${{matrix.dotnet-platform}}

    - name: Download runtime
      shell: bash
      run: |
        curl --location --output qt-runtime.tar.gz https://github.com/qmlnet/qt-runtimes/releases/download/releases/qt-${{matrix.qt-version}}-${{matrix.dotnet-platform}}-runtime.tar.gz
        mkdir -p bin/Release/${{matrix.dotnet-version}}/${{matrix.dotnet-platform}}/publish/qt-runtime
        tar -xf qt-runtime.tar.gz -C bin/Release/${{matrix.dotnet-version}}/${{matrix.dotnet-platform}}/publish/qt-runtime

    - name: Zip up artifact
      shell: bash
      run: cd bin/Release/${{matrix.dotnet-version}}/${{matrix.dotnet-platform}}/publish/ && 7z a -tzip $GITHUB_WORKSPACE/publish/Hammer-${{matrix.deployment-platform}}.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hammer-${{matrix.buildname}}
        path: publish/*


  upload_artifacts:
    name: Upload to pre-release
    runs-on: ubuntu-20.04
    needs: build
    if: github.event_name == 'push'

    steps:
    - uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Deploy to a preview link
      uses: marvinpinto/action-automatic-releases@v1.2.0
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        prerelease: true
        automatic_release_tag: latest
        title: Latest in-development build
        files: |
          artifacts/hammer-linux/Hammer-linux.zip
          artifacts/hammer-windows/Hammer-windows.zip
          artifacts/hammer-macos/Hammer-macos.zip

  validate_examples_metadata:
    name: Validate examples metadata file

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if metadata or schema have changed
        id: changed-files-specific
        uses: tj-actions/changed-files@v6.3
        with:
          files: |
            assets/examples/.metadata.schema.json
            assets/examples/metadata.json

      - name: Set up npm
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Install ajv
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: npm install -g ajv-cli

      - name: Validate metadata
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: ajv -s assets/examples/.metadata.schema.json -d assets/examples/metadata.json
