name: Update website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if metadata or schema have changed
        id: readme-updated
        uses: tj-actions/changed-files@v12
        with:
          files: README.md
      
      - name: Install github-to-readme-html
        run: npm install github-readme-to-html
      
      - name: Generate HTML
        run: npx github-readme-to-html --title "Hammer - simple, reliable FHIR validator"
        
      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.2
        with:
          source-directory: dist
